services:
  - type: web
    name: quickrecharge-frontend
    env: static
    buildCommand: npm install && npx vite build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production